// Static review stats for the landing reviews section. The review cards
// themselves are screenshots in public/reviews/ (see app/reviews-manifest.json,
// generated by scripts/gen-reviews-manifest.mjs at prebuild).
export const REVIEW_STATS = { average: 5.0, total: 38 };
