// Social-proof counts shown across the landing pages and the hub. Change
// them here only; every "450+" / "127 reviews" reads from this object.
export const TRUST_COUNTS = {
  students: 450,
  reviews: 127,
} as const;

// Static review stats for the landing reviews section. The review cards
// themselves are screenshots in public/reviews/ (see app/reviews-manifest.json,
// generated by scripts/gen-reviews-manifest.mjs at prebuild).
// Keep in sync with TRUST_COUNTS.reviews (derived, so it cannot drift).
export const REVIEW_STATS = { average: 4.9, total: TRUST_COUNTS.reviews };
