-- Learn system: reset seed data and load the real 4-section curriculum.
-- Replaces the placeholder seeds from learn/004 and learn/005.
-- NOTE: deleting lessons cascades to user_lesson_progress rows; fine pre-launch,
-- but do not re-run casually once real users have progress.

-- Wipe old seed data
DELETE FROM lessons;
DELETE FROM courses;

-- New courses matching real curriculum
INSERT INTO courses (slug, title, description, category, tier, sort_order, is_published) VALUES
  ('foundations', 'Foundations', 'The base you need before any deal. Understand the game, the two paths, and what makes ours different.', 'beginner', 'base', 1, true),
  ('finding-deals-and-buyers', 'Finding Deals & Buyers', 'Buyer-first thinking, on-market vs off-market, and how to analyze deals like a pro.', 'beginner', 'base', 2, true),
  ('closing-the-deal', 'Closing the Deal', 'Acquisitions, contracts, dispositions, and getting paid at title.', 'intermediate', 'base', 3, true),
  ('scaling', 'Scaling', 'Reinvest smart, systemize, and see how top students are running it.', 'advanced', 'base', 4, true);

-- Foundations lessons (3)
INSERT INTO lessons (course_id, slug, title, description, content, sort_order, is_published) VALUES
  ((SELECT id FROM courses WHERE slug = 'foundations'), 'orientation-and-expectations', 'Orientation & Expectations', 'Set your goals and understand how to get the most out of Real Venture.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Welcome to Real Venture. This orientation covers what to expect, how to use the platform, and the mindset needed to close your first deal in 14 days."}]'::jsonb, 1, true),
  ((SELECT id FROM courses WHERE slug = 'foundations'), 'what-wholesaling-actually-is', 'What Wholesaling Actually Is', 'Cut through the noise. Learn what wholesaling really is (and is not).', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Wholesaling is not what most YouTubers make it look like..."},{"type":"quiz","id":"q1","question":"Which of the following best describes wholesaling?","options":["Buying and holding rental properties","Finding motivated sellers and assigning the contract to a cash buyer","Flipping houses and renovating them","Building new construction homes"],"correct":1,"explanation":"Wholesaling is finding motivated sellers and assigning the contract to a cash buyer for an assignment fee."}]'::jsonb, 2, true),
  ((SELECT id FROM courses WHERE slug = 'foundations'), 'traditional-vs-secured-wholesaling', 'Traditional vs Secured Wholesaling', 'The two paths. Why we teach secured wholesaling and what makes it different.', '[{"type":"text","body":"Traditional wholesaling: find a deal, hope you can find a buyer. Secured wholesaling: find the buyer first, then find their deal. Here is why this changes everything."},{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"quiz","id":"q1","question":"What is the core difference in secured wholesaling?","options":["You use a different contract","You find the buyer before the deal","You partner with an agent","You only work off-market"],"correct":1,"explanation":"Secured wholesaling flips the traditional model by locking in the buyer first, then hunting for the exact deal they want."}]'::jsonb, 3, true);

-- Finding Deals & Buyers lessons (4)
INSERT INTO lessons (course_id, slug, title, description, content, sort_order, is_published) VALUES
  ((SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers'), 'how-to-find-a-buyer', 'How to Find a Buyer', 'Start here. Build your buyer list before you touch a deal.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Buyers are the foundation of everything. Here is exactly where to find them, what to ask, and how to lock them in for repeat business."},{"type":"quiz","id":"q1","question":"What should you always do before analyzing a deal?","options":["Run comps","Talk to the seller","Have a buyer in mind","Get the contract signed"],"correct":2,"explanation":"Always know who your buyer is before you spend time analyzing. This is the core of secured wholesaling."}]'::jsonb, 1, true),
  ((SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers'), 'on-market', 'On-Market Strategy', 'Zillow, Redfin, MLS. Find deals in plain sight that everyone else is missing.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"On-market deals are hiding in plain sight. Here is our exact process for finding them on Zillow and getting them under contract."}]'::jsonb, 2, true),
  ((SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers'), 'off-market', 'Off-Market Strategy', 'Skip trace, direct mail, cold call. Build a deal flow that competitors cannot touch.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Off-market takes more work but the deals are bigger. Here is the full playbook."},{"type":"quiz","id":"q1","question":"What is the biggest advantage of off-market deals?","options":["They are easier to find","Less competition means better margins","They close faster","They require no negotiation"],"correct":1,"explanation":"Off-market means fewer eyes on the deal, which usually translates to better assignment fees."}]'::jsonb, 3, true),
  ((SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers'), 'deal-analysis-and-underwriting', 'Deal Analysis & Underwriting', 'Pull comps, calculate ARV, set your max offer. Never guess again.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Bad numbers kill deals. This lesson walks you through the exact math and how to use the Studio deal analyzer to speed it up."},{"type":"action","label":"Try the Deal Analyzer","href":"https://realventurestudio.com/analyzer"}]'::jsonb, 4, true);

-- Closing the Deal lessons (4)
INSERT INTO lessons (course_id, slug, title, description, content, sort_order, is_published) VALUES
  ((SELECT id FROM courses WHERE slug = 'closing-the-deal'), 'acquisitions-and-getting-the-contract', 'Acquisitions & Getting the Contract', 'The seller call. Lock in the price and get the contract signed.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"This is where deals live or die. The exact scripts, objections, and closing techniques we use every day."}]'::jsonb, 1, true),
  ((SELECT id FROM courses WHERE slug = 'closing-the-deal'), 'how-to-fill-out-and-sign-the-contract', 'How to Fill Out & Sign the Contract', 'Every field, every clause. Walk through the exact contract we use.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Contract mistakes cost deals. This walkthrough covers every field of the Real Venture contract, what it means, and how to fill it out."},{"type":"quiz","id":"q1","question":"What is the most important clause to include as a wholesaler?","options":["Right to inspect","Right to assign","Financing contingency","Closing date extension"],"correct":1,"explanation":"The right to assign is what makes wholesaling possible. Without it, you cannot transfer the contract to your buyer."}]'::jsonb, 2, true),
  ((SELECT id FROM courses WHERE slug = 'closing-the-deal'), 'dispositions-and-selling-the-contract', 'Dispositions & Selling the Contract', 'Get the contract in front of buyers. Close the deal fast.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"Once you have the contract, speed matters. Here is how to market the deal, negotiate with buyers, and lock in your assignment fee."}]'::jsonb, 3, true),
  ((SELECT id FROM courses WHERE slug = 'closing-the-deal'), 'title-work-and-getting-paid', 'Title Work & Getting Paid', 'The closing table. Title company, wire, done.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"The last mile. What happens at title, how the wire works, and what to do to make sure the check hits."}]'::jsonb, 4, true);

-- Scaling lessons (2)
INSERT INTO lessons (course_id, slug, title, description, content, sort_order, is_published) VALUES
  ((SELECT id FROM courses WHERE slug = 'scaling'), 'reinvesting-and-scaling', 'Reinvesting & Scaling', 'What to do with your first check. Systemize, hire, and grow.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"First deal is the hardest. Second through tenth is where the money is. How to reinvest smart and build a real business."}]'::jsonb, 1, true),
  ((SELECT id FROM courses WHERE slug = 'scaling'), 'case-studies', 'Case Studies', 'Real deals from real students. Break down the wins and the lessons.', '[{"type":"video","youtube_id":"PLACEHOLDER"},{"type":"text","body":"See exactly how top students closed their first, fifth, and tenth deals. Numbers, timelines, mistakes, all of it."}]'::jsonb, 2, true);
