-- 009_full_quizzes.sql
-- Expand each lesson from 1 quiz question to 5. Rebuilds the content JSONB
-- for all 13 lessons, preserving video block and text block, replacing the
-- single quiz block with a quiz array (5 questions each, ids q1-q5).
-- Idempotent: safe to re-run.

-- =============================================================================
-- FOUNDATIONS
-- =============================================================================

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"m6FAvTl5Woo"},
    {"type":"text","body":"Welcome to Real Venture. This program walks you through the entire wholesaling process from finding your first deal to scaling into a real business. There are multiple paths you can take, and none of them is universally best. There is a best path for you based on your capital, your risk tolerance, and how fast you want to move.\n\nThe way to win here is simple. Take consistent action, ask questions when you get stuck, and do not rush the process. Every student who has closed a deal did the same thing. They kept going. The first 30 days are about understanding the process and starting real conversations. By 60 days you have leads coming in. Around 90 days your first deal closes and you get paid. Some move faster. Some take longer. What matters is that you stay in the game.\n\nDo not fall into analysis paralysis. Watch the modules in order, take notes, and then take unprepared action. Step two reveals itself once you take step one. If you get stuck, that is what the Discord and Loom reviews are for. This is a business, not a lottery ticket, but when it clicks it clicks fast."},
    {"type":"quiz","id":"q1","question":"What is the most important behavior for succeeding in this program?","options":["Waiting until you understand every detail before taking action","Taking consistent action and asking questions when stuck","Skipping ahead to the modules about getting paid","Watching every module twice before doing anything"],"correct":1,"explanation":"Consistent action is the pattern behind every student win."},
    {"type":"quiz","id":"q2","question":"About how long does it typically take for a first deal to close?","options":["1 to 2 weeks","30 days","Around 90 days","A full year"],"correct":2,"explanation":"First 30 days you learn the process. Around 60 days leads come in. Around 90 days the first deal closes."},
    {"type":"quiz","id":"q3","question":"What is unprepared action?","options":["Waiting until you have every answer before starting","Taking the next step even before you feel fully ready","Copying someone else exact strategy","Paying for a done-for-you service"],"correct":1,"explanation":"Take step one and step two reveals itself. Dont sit in analysis paralysis."},
    {"type":"quiz","id":"q4","question":"What is Real Venture at its core?","options":["A real business that requires consistency","A lottery ticket","A get-rich-quick scheme","A passive income product"],"correct":0,"explanation":"Its a business, not a lottery ticket. When it clicks, it clicks fast, but you have to stay in the game."},
    {"type":"quiz","id":"q5","question":"What is the Discord and Loom review support for?","options":["Doing the thinking for you so you dont have to","Helping you think clearly and stay accountable","Automatically closing deals on your behalf","Getting free leads sent to you"],"correct":1,"explanation":"The mentorship teaches you how to operate independently. It supports you, it doesnt replace your work."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'foundations') AND sort_order = 1;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"RT_ATaMI88k"},
    {"type":"text","body":"At its core, wholesaling is controlling a deal, not buying a house. You find a seller who wants speed or certainty, you put the property under contract at a price that makes sense for an investor, and then you sell that contract to a cash buyer for more than you have it under contract for. You never own the house. You are the deal sourcer, and you get paid for presenting an opportunity to someone who can actually close on it.\n\nThe money comes from spreads. Investors will pay for deals they cannot easily source themselves, and your fee lives inside the gap between what a seller will accept and what a buyer will pay. If there is no real spread, there is no deal. Wholesalers do not force profits. They discover them.\n\nMost people fail before deal one because they chase tactics instead of understanding deals. They look for the perfect script, avoid talking to real sellers, and quit right before momentum shows up. The truth is you do not need to be a great salesperson. If you can have a normal conversation with a human and actually want to solve a problem, you can make money doing this."},
    {"type":"quiz","id":"q1","question":"When you wholesale a property, what are you actually selling?","options":["The house itself","Your right to buy the property under the contract","A share of ownership in the property","A loan against the property"],"correct":1,"explanation":"You are selling the contract, not the house. You never take ownership."},
    {"type":"quiz","id":"q2","question":"Where does the wholesalers money come from?","options":["A monthly fee paid by the seller","The spread between what the seller accepts and what the buyer pays","A commission from the real estate agent","Renting the house out for a month first"],"correct":1,"explanation":"Your fee lives inside the gap. If theres no real spread, theres no deal."},
    {"type":"quiz","id":"q3","question":"How do you calculate the profit on a wholesale deal?","options":["The list price minus the propertys tax value","The price the buyer pays minus the price you have it under contract for","The ARV minus the repair costs","Ten percent of the sale price"],"correct":1,"explanation":"Your profit is the spread between what your buyer pays and what youve locked the contract at with the seller. Thats your assignment fee."},
    {"type":"quiz","id":"q4","question":"What is the wholesalers actual job?","options":["Sourcing deals for investors who can close on them","Being a licensed real estate agent","Renovating and flipping houses","Lending money to home buyers"],"correct":0,"explanation":"Youre not a realtor, flipper, or lender. Youre a deal sourcer."},
    {"type":"quiz","id":"q5","question":"Why do most beginners fail before their first deal?","options":["They talk to too many sellers","They chase tactics instead of understanding deals","They spend too much money on marketing","They watch the modules in order"],"correct":1,"explanation":"They look for the perfect script, avoid real conversations, and quit right before momentum shows up."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'foundations') AND sort_order = 2;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"-RVMXpyyiwM"},
    {"type":"text","body":"There are two very different ways to wholesale, and they carry very different risk profiles. Traditional wholesaling is what most people learn first. You find a seller, put the property under contract, and then hunt for a buyer during the inspection period. The risk is that if the buyer hesitates, the deal dies and you are stuck.\n\nSecured wholesaling flips the order. You find the buyer first, learn their exact buy box, and then source deals that already fit their demand. You lock the contract knowing the exit is already lined up. Dispo risk gets removed upstream. The inspection becomes a formality instead of a scramble.\n\nBoth approaches work, but they are not equal for beginners. Traditional shines when you already have capital, an established buyers list, and can absorb a deal falling through. Secured shines when you are starting out and cannot afford to have your first four contracts blow up. Every student result on the secured side comes from the same pattern: buyer first, then deal."},
    {"type":"quiz","id":"q1","question":"What is the key difference in secured wholesaling?","options":["You buy the property yourself before reselling it","You find the buyer first, then source deals that fit their buy box","You only work with off-market deals","You never sign a contract until after inspection"],"correct":1,"explanation":"Secured means locking in a buyers buy box before you go find the deal."},
    {"type":"quiz","id":"q2","question":"In traditional wholesaling, what happens if the buyer hesitates?","options":["The seller lowers their price","The deal can die and you can get stuck","The title company covers the loss","The buyer pays a penalty fee"],"correct":1,"explanation":"Thats the risk. Traditional depends on finding a buyer during the inspection period."},
    {"type":"quiz","id":"q3","question":"Which approach is generally safer for beginners?","options":["Traditional wholesaling","Secured wholesaling","Both are equally risky","Neither works for beginners"],"correct":1,"explanation":"Secured removes dispo risk upstream. Beginners cant afford four contracts blowing up."},
    {"type":"quiz","id":"q4","question":"When does traditional wholesaling shine?","options":["When youre brand new with no money","When you have capital and can absorb a deal falling through","When you have zero buyers on your list","When you refuse to talk to real estate agents"],"correct":1,"explanation":"Traditional works if you already have infrastructure and financial cushion."},
    {"type":"quiz","id":"q5","question":"What does secured wholesaling do to the inspection period?","options":["It removes it entirely","It turns it into a formality instead of a scramble","It extends it to 30 days","It makes it more stressful"],"correct":1,"explanation":"Because the buyer is already locked, inspection is a check, not a scramble to find someone."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'foundations') AND sort_order = 3;

-- =============================================================================
-- FINDING DEALS & BUYERS
-- =============================================================================

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"I1vSZZoXsqQ"},
    {"type":"text","body":"Finding a buyer is not about luck. It is about picking the right channel for where you are right now. Every channel trades something different. Time, money, control, or predictability. There is always something you give up.\n\nThere are four main levels. Facebook groups and DMs are free but slow and require hustle. Discord investor communities are where relationships actually get built, and this is where William found his biggest VIP buyer. JVing with other wholesalers is the fastest path to your first deal because you plug into someone who already has buyers. PropStream and public records give you the highest-intent buyers because they have already closed deals with cash, but it requires cold calling.\n\nContribute before you extract. These buyers do not care about you until you are useful to them. Provide value first, make friends, and the deals will follow. And no matter which channel you use, track everything in a simple spreadsheet: buyer name, buy box, contact info, where they buy. That list becomes your leverage."},
    {"type":"quiz","id":"q1","question":"What is the most important thing to do when reaching out to buyers in Discord communities?","options":["Ask for their buy box immediately","Contribute value before asking for anything","Post about your deals in every channel","Pay for a premium membership"],"correct":1,"explanation":"These buyers already work with wholesalers. You have to be useful first."},
    {"type":"quiz","id":"q2","question":"Which channel is completely free but requires the most hustle?","options":["Facebook groups and DMs","Google ads","PropStream lists","Full-time virtual assistants"],"correct":0,"explanation":"Facebook is fastest to enter and free. You trade effort for access."},
    {"type":"quiz","id":"q3","question":"What is JVing with another wholesaler?","options":["Splitting the assignment fee with someone who brings a buyer or a deal","Selling the house together and both taking ownership","Paying a fee to another wholesaler for a lead","Buying the other wholesalers business"],"correct":0,"explanation":"One person brings the deal, one brings the buyer. You split the fee."},
    {"type":"quiz","id":"q4","question":"What should you track for every buyer you find?","options":["Just their phone number","Their name, buy box, contact info, and where they buy","Only their name and how much cash they have","You should never track buyers in a spreadsheet"],"correct":1,"explanation":"A simple spreadsheet becomes your leverage. That list is the business."},
    {"type":"quiz","id":"q5","question":"Why is Discord often better than Facebook for finding buyers?","options":["Discord buyers always pay more","Discord has more actual relationships and less transactional messages","Discord is more expensive to join","Discord requires a real estate license"],"correct":1,"explanation":"Facebook is transactional. Discord tends to have actual community and real relationships."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers') AND sort_order = 1;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"PT2ehPhSdlM"},
    {"type":"text","body":"On-market wholesaling means finding deals on Zillow or the MLS and negotiating terms with the listing agent. Most wholesalers ignore it because they assume listed prices leave no room for a discount. That is wrong. Discounts absolutely exist when a listing has been sitting for 60 or 90 days, has price cuts, or the property is in a condition that most retail buyers cannot get financed on.\n\nThe edge is speed, clean data, and clear comps. Every piece of information you need is already on the listing: address, square footage, bed and bath count, photos, and sold comps in the area. That makes underwriting fast. Your job is to know your buyer buy box first, then use Zillow filters (days on market, price cuts, home type, keywords like as-is or cash only) to shortlist properties that could actually work.\n\nWhen you talk to the listing agent, keep it simple. Position yourself as serious, unrepresented, with proof of funds. Ask about condition, close date, existing offers, and whether the seller will accept as-is terms. If the numbers do not work after light underwriting, kill the deal fast. Almost-works deals steal your time. Your minimum spread rules exist for a reason."},
    {"type":"quiz","id":"q1","question":"What is the biggest signal that an on-market listing might accept a discount?","options":["The listing has professional photos","The property has been on the market for a long time with price cuts","The listing is in a great neighborhood","The listing agent is easy to reach"],"correct":1,"explanation":"Long days on market plus price cuts means the seller is tired."},
    {"type":"quiz","id":"q2","question":"What is the wholesalers edge with on-market deals?","options":["Bigger discounts than off-market","Speed, clean data, and clear comps","Access to secret listings","Lower title company fees"],"correct":1,"explanation":"Everything is on Zillow. Address, square footage, photos, comps. Underwriting is fast."},
    {"type":"quiz","id":"q3","question":"When talking to a listing agent, how should you position yourself?","options":["As a serious cash buyer with proof of funds","As a shopper who might make an offer","As another real estate agent","As a friend of the seller"],"correct":0,"explanation":"Agents are filtering for two things: will you close, or will you waste their time."},
    {"type":"quiz","id":"q4","question":"What should you do with a deal where the numbers barely work?","options":["Push forward and hope it works out","Kill it fast and move on","Wait a few weeks and try again","Lower your assignment fee to make it work"],"correct":1,"explanation":"Almost-works deals steal your time. Your minimum spread rules exist for a reason."},
    {"type":"quiz","id":"q5","question":"Why can you get discounts on properties in poor condition?","options":["Buyers with regular financing usually cant get loans on them","Sellers legally have to accept low offers","The city forces the seller to sell","Agents dont want to list them anyway"],"correct":0,"explanation":"Retail buyers cant get financed on rough properties, so cash offers can win."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers') AND sort_order = 2;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"ZZBdY5SBjwU"},
    {"type":"text","body":"Off-market wholesaling exists because not every seller wants the open market. Some want speed, privacy, or are dealing with a situation that makes listing painful. Off-market does not automatically produce better deals. It creates different access, and that access costs time, money, or management.\n\nThere are four main tiers. SMS text blasting is the cheapest way in, roughly 500 to 2500 dollars per month, and it works but requires strong filtering because most leads will not convert. Virtual assistants let you scale outreach without doing the calls yourself, typically 1500 to 3500 dollars per month, and the results depend on your systems more than the VAs. Facebook ads bring inbound leads at 3000 to 6000 dollars per month with better predictability, but they punish sloppy operators. Google ads are the highest-intent leads at 6000 to 10000 dollars per month, and they are best once your buyers and numbers are already dialed in.\n\nDo not start with off-market. It exposes weaknesses fast. Without buyer clarity, every lead looks good. Without confidence in your numbers, every call feels stressful. Off-market rewards operators who filter decisively, not beginners looking for a shortcut. Layer it in once you have proof of concept from on-market or JV deals first."},
    {"type":"quiz","id":"q1","question":"Which off-market channel is the cheapest way to start?","options":["Google ads","Facebook ads","SMS text blasting","Hiring a full team of VAs"],"correct":2,"explanation":"SMS is the lowest cost entry, roughly 500 to 2500 dollars per month."},
    {"type":"quiz","id":"q2","question":"Which channel brings the highest-intent leads but costs the most?","options":["Google ads","SMS text blasting","Cold calling","Facebook groups"],"correct":0,"explanation":"Google ads catch people actively searching to sell. Highest intent, highest cost."},
    {"type":"quiz","id":"q3","question":"Why should beginners avoid starting with off-market?","options":["Its illegal for beginners","It punishes weak systems and unclear buyer criteria fast","It requires a real estate license","It only works in big cities"],"correct":1,"explanation":"Without buyer clarity, every lead looks good. Off-market exposes weaknesses fast."},
    {"type":"quiz","id":"q4","question":"What does a virtual assistant (VA) mainly help you do?","options":["Sign contracts on your behalf","Scale outreach without doing the calls yourself","Pay for your marketing","Fund your first deal"],"correct":1,"explanation":"VAs replace the repetition. Your systems and training make them effective."},
    {"type":"quiz","id":"q5","question":"When someone hits you up on Facebook without qualifying, what should you do?","options":["Send them the address immediately","Send an intake link to filter serious buyers","Block them","Give them a discount to lock them in"],"correct":1,"explanation":"An intake link with proof of funds and timeline questions filters 80 percent of the noise."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers') AND sort_order = 3;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"QWiUA_8Prco"},
    {"type":"text","body":"This is the most important module in the entire curriculum. If you do not understand the numbers, you will waste weeks on deals that were never going to close. The goal here is to be able to look at any property and quickly decide: is this a real deal, or is it a distraction?\n\nStart with fact-finding. You need the condition, the confirmed square footage, the age of the roof and HVAC, and photos or video of the inside. Then you pull sold comps on Zillow within the past six months, same square footage range (plus or minus 250 sq ft), same property type, in the same pocket. Do not cherry-pick comps to make the deal work. Pick honest anchors: one low comp, one high comp, and two to four in between. That gives you a real ARV range.\n\nOnce you have ARV and repair estimates, run the MAO formula: Max Allowable Offer equals ARV times 0.70 minus Repairs minus Your Fee. Seventy percent is the standard discount anchor for flippers in most markets. If the math only works when you round everything in your favor, it is not a deal. Kill it and move on."},
    {"type":"quiz","id":"q1","question":"What does ARV stand for?","options":["Average Rental Value","After Repair Value","Assigned Real Value","Approved Realtor Value"],"correct":1,"explanation":"ARV is what the property is worth after being fully repaired."},
    {"type":"quiz","id":"q2","question":"When comping a property on Zillow, how far back should sold comps ideally be?","options":["Within the past 6 months","Within the past 2 years","Any time in history","Within the past 5 years"],"correct":0,"explanation":"Six months keeps comps current. Twelve months only if the area doesnt have enough recent sales."},
    {"type":"quiz","id":"q3","question":"What is the standard MAO (Max Allowable Offer) formula?","options":["ARV times 0.70 minus Repairs minus Your Fee","ARV plus Repairs plus Your Fee","ARV times 1.30 minus Repairs","Repairs times 3 plus Your Fee"],"correct":0,"explanation":"Seventy percent is the standard flipper discount. Subtract repairs and your fee."},
    {"type":"quiz","id":"q4","question":"What is a comp?","options":["A price the seller is asking for","A similar sold property used to figure out value","A comparison of two real estate agents","A compensation fee paid to the buyer"],"correct":1,"explanation":"A comp is a similar recently-sold property used to support the ARV."},
    {"type":"quiz","id":"q5","question":"When picking comps, what should you avoid?","options":["Comps that are the same size as your subject property","Cherry-picking only comps that make the deal look good","Comps that are in the same neighborhood","Comps from the past six months"],"correct":1,"explanation":"Cherry-picking wastes your time. Pick honest anchors, high and low."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'finding-deals-and-buyers') AND sort_order = 4;

-- =============================================================================
-- CLOSING THE DEAL
-- =============================================================================

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"zuiIhmvRZcM"},
    {"type":"text","body":"This is where the deal actually happens. The first call with a seller is about learning whether the situation makes sense to keep working. Set expectations early, respect their time, and be human. You are not reading a script. You are having a conversation.\n\nOpen with context (where the lead came from), ask what they are looking to get for the property, then dig into the situation: who occupies the property, the condition, timeline, and motivation. If the price they want is dramatically higher than your max allowable offer, be honest that the number probably will not work, but ask if it is worth walking through the details anyway. If you are talking to a real estate agent on an on-market deal, skip the motivation questions. It just makes you sound green.\n\nDo not make your offer on the first call. Get all the info, do your real underwriting, then schedule a follow-up call to deliver the number. When you deliver, set expectations first, explain the logic, and keep the relationship intact no matter where the number lands. If they say no, put them in your follow-up sequence. The money is made in the follow-up. Deals come back weeks or months later all the time."},
    {"type":"quiz","id":"q1","question":"When should you deliver your actual offer to the seller?","options":["Immediately on the first call to lock them in","On a scheduled follow-up call after you have done real underwriting","Only after they sign a contract","By text message right after the first call"],"correct":1,"explanation":"Use the first call for info. Deliver the offer on a follow-up after real underwriting."},
    {"type":"quiz","id":"q2","question":"If a seller wants way more than your max offer, what should you do?","options":["Immediately agree to their price","Be honest, walk them through the number, and put them on follow-up","Hang up on them","Send them a legal letter"],"correct":1,"explanation":"Deals often come back weeks or months later. The money is made in the follow-up."},
    {"type":"quiz","id":"q3","question":"When talking to a real estate agent on an on-market deal, what should you skip?","options":["Asking about the condition","Asking about seller motivation","Confirming the close date","Confirming the price"],"correct":1,"explanation":"Motivation questions on-market make you sound green. The agent is already trying to sell."},
    {"type":"quiz","id":"q4","question":"What is the point of the fact-finding portion of a seller call?","options":["To pressure the seller into signing","To gather condition, timeline, and situation info before making an offer","To sell the seller on your credentials","To lock the seller into a verbal contract"],"correct":1,"explanation":"You need condition, occupancy, and timeline before you can make a real offer."},
    {"type":"quiz","id":"q5","question":"What is the negotiation move called put them on hold?","options":["Ending the call and never following up","Muting the phone for 1-2 minutes so the offer bump feels deliberate","Passing the phone to your business partner","Recording the call for legal purposes"],"correct":1,"explanation":"You avoid back-and-forth negotiation live. Step away, review, come back with a considered adjustment."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'closing-the-deal') AND sort_order = 1;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"0zYgXGedPyg"},
    {"type":"text","body":"Once you have a verbal agreement, the next step is turning it into a signed, enforceable contract. There are two paths depending on how you found the deal. For off-market deals, you write up the contract yourself using a Purchase and Sale Agreement (PSA) template and send it through DocuSign. For on-market deals, the listing agent writes the contract on state forms and sends it to you to sign.\n\nOn off-market, keep it simple. Download the PSA template, fill in the buyer and seller info, the property address, purchase price, earnest money deposit, and closing date. Send it through DocuSign with the signature boxes pre-placed so the seller only has to click sign. Do not make them fill anything out. Reduce friction to zero.\n\nOn on-market, the agent will send you their state PSA. Always review the sellers disclosure carefully, confirm the earnest money amount and inspection period, and make sure the terms match what you agreed to on the call. It is the signature that makes the contract enforceable, not the form. If you are unsure about anything, ask before you sign. An LLC is recommended once you are doing regular deals, but you can close your first deal or two without one."},
    {"type":"quiz","id":"q1","question":"What makes a purchase contract legally enforceable?","options":["Being on official state forms","Having a notary present","The signatures of the parties","Being reviewed by a lawyer"],"correct":2,"explanation":"The signatures make it enforceable, not the form itself."},
    {"type":"quiz","id":"q2","question":"For an off-market deal, who writes the contract?","options":["You do, using a PSA template","The listing agent","The title company","The buyer"],"correct":0,"explanation":"Off-market has no agent, so you write it and send through DocuSign."},
    {"type":"quiz","id":"q3","question":"For an on-market deal, who writes the contract?","options":["You do","The listing agent writes it on state forms","The seller writes it themselves","The title company writes it"],"correct":1,"explanation":"On-market means the agent uses state forms. You review and sign."},
    {"type":"quiz","id":"q4","question":"When sending a contract to a seller via DocuSign, what should you do?","options":["Send an empty template and let them fill it out","Pre-fill every field so all they have to do is click sign","Meet them in person to sign","Have them sign a scan of a paper form"],"correct":1,"explanation":"Reduce friction to zero. The seller should only need to click sign."},
    {"type":"quiz","id":"q5","question":"Is an LLC required to close your first deal?","options":["Yes, always","No, but it is recommended once you do regular deals","Yes, but only in certain states","No, you never need one"],"correct":1,"explanation":"You can close your first deal or two without one. Set up an LLC once youre doing regular volume."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'closing-the-deal') AND sort_order = 2;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"gnf5lnrqdI4"},
    {"type":"text","body":"Dispositions is deal packaging. Your job is to make a buyer say send it without a 20 minute pitch. Good packaging means clean photos, clear numbers, honest condition notes, real comps, and terms upfront. Bad packaging is vague marketing copy with no comps, no rehab estimate, and no evidence.\n\nDecide up front whether you are blasting or auctioning. Blasting is for average deals with average demand and you want speed. Auctioning is for the bangers where you already know multiple buyers will want it. Then release in tiers: your A-list buyers first (the ones you have closed with before), then direct outreach to a cash buyer list, then JV partners, then Facebook groups last. Facebook is the noisiest channel with the lowest signal.\n\nGate everything. Before you send the address, require proof of funds, close-by date, and confirmation the buyer can wire EMD. That single filter kills 80 percent of the tire kickers. Once a buyer is locked (assignment signed, EMD deposited to title, walkthrough scheduled), keep a backup buyer warm in case the first one flakes. Most deals die not from bad numbers but from sloppy paperwork and nobody driving the timeline."},
    {"type":"quiz","id":"q1","question":"What should you require before sending property details to a new buyer?","options":["A friendly introduction message","Proof of funds and close-by date","A signed non-disclosure agreement","Their social media profile"],"correct":1,"explanation":"Gating on proof of funds kills 80 percent of tire kickers immediately."},
    {"type":"quiz","id":"q2","question":"What is the difference between blasting and auctioning a deal?","options":["Blasting is illegal, auctioning is legal","Blasting is for average deals with speed; auctioning is for known bangers","Auctioning is only for houses over 500K","Blasting only works on Facebook"],"correct":1,"explanation":"Blast for speed on regular deals. Auction when you know multiple buyers want it."},
    {"type":"quiz","id":"q3","question":"Which buyer channel should you release a deal to first?","options":["Your A-list buyers you have closed with before","Random Facebook groups","Craigslist ads","Newspaper listings"],"correct":0,"explanation":"Highest-intent, fastest EMD, cleanest close. A-list first, Facebook last."},
    {"type":"quiz","id":"q4","question":"What is a backup buyer?","options":["A buyer you keep secret from your main buyer","A qualified buyer ready to step in if your primary flakes","A buyer that funds you if youre short on cash","A buyer that lives in a backup city"],"correct":1,"explanation":"Always keep the second-best buyer warm. Insurance if the primary bails."},
    {"type":"quiz","id":"q5","question":"Why do most deals die?","options":["Because the numbers are bad","Because paperwork gets sloppy and nobody drives the timeline","Because interest rates change","Because the seller changes their mind"],"correct":1,"explanation":"Bad numbers get killed early. Sloppy execution kills the deals you thought were closing."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'closing-the-deal') AND sort_order = 3;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"bjTVjrzmdqw"},
    {"type":"text","body":"Once you have a signed PSA and a signed assignment agreement, the next step is opening the file with a title company. Title verifies ownership, runs a title search for liens or back taxes, prepares closing documents, coordinates funds, and gets everyone paid.\n\nUse a title company that is assignment friendly. Either use one we recommend, or find a local one and ask three questions on the first call: Are you familiar with assignment contracts? Do you handle double closes? Do you allow pass-through funding on double closes? If they sound confused or unsure, walk away. Not every title company understands investor deals, and a confused title company will kill your closing timeline.\n\nThere are two ways you get paid. On an assignment, your fee shows up on the settlement statement and title wires it to you at closing. On a double close, you have two separate contracts (A-to-B and B-to-C), and your fee is the spread between them. It is not disclosed on either settlement statement. Ninety percent of your deals will be assignments. In both cases, title pays you, not the buyer. Once closing docs are signed and funds wire in, you typically get paid same day or the next business day."},
    {"type":"quiz","id":"q1","question":"On a wholesale deal, who actually sends you your assignment fee?","options":["The end buyer directly","The seller","The title company","Your real estate agent"],"correct":2,"explanation":"Title handles all money at closing. They wire you the fee."},
    {"type":"quiz","id":"q2","question":"What is a title companys main job?","options":["To find buyers for you","To verify ownership, run title, and coordinate closing funds","To underwrite the deal for you","To advertise the property"],"correct":1,"explanation":"Title verifies the seller owns it, runs a search for liens, and coordinates the money."},
    {"type":"quiz","id":"q3","question":"When calling a new title company, what should you always ask?","options":["Are you familiar with assignment contracts?","Do you have a physical office?","How many employees do you have?","What software do you use?"],"correct":0,"explanation":"If they sound confused about assignments, walk away. Not every title company understands investor deals."},
    {"type":"quiz","id":"q4","question":"Whats the difference between an assignment and a double close?","options":["Assignments are illegal, double closes are legal","Assignments show your fee on the settlement statement; double closes use two contracts and hide the spread","Assignments cost more than double closes","There is no real difference"],"correct":1,"explanation":"Assignments are one contract with your fee disclosed. Double closes are two contracts with the spread hidden."},
    {"type":"quiz","id":"q5","question":"How do you typically get paid at closing?","options":["Cash in an envelope","Wire transfer, same day or next business day","Personal check that clears in 30 days","Cryptocurrency"],"correct":1,"explanation":"Wire is standard. You get paid same day or the next business day after closing."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'closing-the-deal') AND sort_order = 4;

-- =============================================================================
-- SCALING
-- =============================================================================

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"7dfPQjGJ0es"},
    {"type":"text","body":"Your first check is fuel, not a finish line. The most common mistake beginners make is closing their first deal, celebrating, spending most of the check on lifestyle, and then wondering why the next month is empty. One deal becomes a paycheck back to zero if you stop feeding the top of the funnel.\n\nThe rule is simple. Before you pay yourself heavy, fund your next month of lead generation. Sixty to eighty percent of your first check should go back into leads: more SMS, more list pulls, more marketing spend. Ten to twenty-five percent should go into basic systems that stop chaos: a simple CRM like GoHighLevel, a dialer, or a VA for ten to twenty hours a week. Five to fifteen percent can be a small win reward if you want one, but only after everything else is funded.\n\nUpgrade your marketing when you can prove you close deals from your current source, when you can afford sixty days of spend without panicking, and when the results are consistent instead of spiky. Start with basic outreach and SMS. Add a VA once volume gets chaotic. Layer in Facebook or Google ads once your process is solid and your dispo is fast. Cheaper lead generation is less predictable. Better lead generation is more predictable. Not more expensive. Better."},
    {"type":"quiz","id":"q1","question":"What should the majority of your first check go toward?","options":["A win reward for yourself","More lead generation for the next month","Paying off personal debt","Software subscriptions"],"correct":1,"explanation":"Sixty to eighty percent back into leads. Thats how you stop being a paycheck-to-zero business."},
    {"type":"quiz","id":"q2","question":"Whats the biggest mistake beginners make after their first deal?","options":["Reinvesting too much money","Stopping the marketing that created the deal","Signing another contract too fast","Hiring too many virtual assistants"],"correct":1,"explanation":"Deals fall through, buyers flake. Lead flow is what makes your business survivable."},
    {"type":"quiz","id":"q3","question":"When should you upgrade to better marketing like Google ads?","options":["When your current system is proven and you can afford 60 days of spend","Right after closing your first deal","Before you close any deals","Only after 5 years in the business"],"correct":0,"explanation":"Predictable lead gen isnt better because its more expensive. Its better because your systems are ready for it."},
    {"type":"quiz","id":"q4","question":"Whats the danger of hiring a closer before you have lead volume?","options":["They will steal your buyers","A closer cant close leads that dont exist","They will charge too much","They will report you to the IRS"],"correct":1,"explanation":"Dont hire people ahead of your lead volume. Fix the top of the funnel first."},
    {"type":"quiz","id":"q5","question":"What is the cycle that keeps a wholesaling business alive?","options":["Leads to conversations to contracts to closings to more leads","Marketing to cashflow to vacation to repeat","Buy to hold to rent to sell","Cold call to close to celebrate to stop"],"correct":0,"explanation":"If closings dont fund more leads, youre back to zero next month."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'scaling') AND sort_order = 1;

UPDATE lessons SET
  content = '[
    {"type":"video","youtube_id":"UsGpg5tI4ZE"},
    {"type":"text","body":"Three real deals from real students, all closed in their first three months. These are the pattern.\n\nDylan found a deal in St. Louis through an agent connection. Locked up at 78K, comps put it at 150K. Got paid 5K on assignment. Two more deals under contract with the same buyer at the time of recording. Roughly 10K in his first 60 days.\n\nMelissa found a property in Scott City, Missouri sitting on Zillow. Had the seller unlist and sell directly. Locked up at 39K after negotiating down from 50K. Comps around 100K. Got paid 4K on assignment. Another deal almost under contract now.\n\nEve found a deal in Granite City, Illinois on Zillow. Made an offer to the listing agent on state forms. Locked up at 60K, comps at 115K. The roof came back bad in inspection so the seller installed a new roof before closing. Got paid 5K, then another 3K on his second deal. Eight thousand cushion in his first three months while working a 60-hour week at his day job. Now scaling with VAs.\n\nWhat is repeatable here is not any specific tactic. It is the pattern. Take action, source deals that match a real buyer, use the profits to buy more opportunities, stack the reps. That is the entire game."},
    {"type":"quiz","id":"q1","question":"What is the common pattern across all three case studies?","options":["They all used the same lead source","They all closed their first deals within three months by taking consistent action","They all had prior real estate experience","They all had large starting budgets"],"correct":1,"explanation":"Different sources, different states. Same pattern: consistent action, fast reps."},
    {"type":"quiz","id":"q2","question":"How did Dylan find his first deal in St. Louis?","options":["Through an agent connection who was teaming up with another wholesaler","By sending SMS blasts","By running Google ads","By cold-calling absentee owners"],"correct":0,"explanation":"Dylans deal came through his agent connection. Assignment of contract, 5K to Dylan."},
    {"type":"quiz","id":"q3","question":"How did Melissa find her first deal in Scott City, Missouri?","options":["Through a Facebook group","Sitting on Zillow. She had the seller unlist it and sell directly","By door-knocking","Through a wholesaler friend"],"correct":1,"explanation":"Melissa found it on Zillow, got it unlisted, and closed direct-to-seller for a 4K assignment."},
    {"type":"quiz","id":"q4","question":"In Eves Granite City deal, what happened during inspection?","options":["The buyer backed out","The roof was bad, but the seller installed a new one before closing","The title company canceled the deal","The seller raised the price"],"correct":1,"explanation":"Seller installed a fresh roof before close. Eve got paid 5K, then 3K on his next deal."},
    {"type":"quiz","id":"q5","question":"What did all three students do with their profits?","options":["Quit their day jobs immediately","Used them to scale their businesses with VAs and more marketing","Spent them on lifestyle upgrades","Bought their first rental properties"],"correct":1,"explanation":"They kept the profits as fuel. Thats the difference between one deal and a real business."}
  ]'::jsonb,
  updated_at = now()
WHERE course_id = (SELECT id FROM courses WHERE slug = 'scaling') AND sort_order = 2;
